### ISSUE TITLE
Resize Columns Automatically in LazyTable

### ISSUE THREAD

**Issue by ikerfah** [oleksandrbalan/lazytable#13]
Hello,

I'm using `LazyTable` for displaying value + unit data. However, I've run into a problem of data not fully displayed:

- Variable Unit Length: Depending on the language, the unit text can sometimes be longer, causing misalignment in the cells.
- Dealing with Large Values: When the values are large, they don't fit well within the standard cell width, getting cut off.

Is there a way to make the column width adjust automatically based on the content? This would help ensure that both longer unit texts and larger values are presented correctly.

Thanks a lot for your work on this library!

**Comment by oleksandrbalan** [comment]
That could be tricky, because items are lazy loaded, and when they are out-of-viewport they are not rendered and not measured.

<image src="https://github.com/oleksandrbalan/lazytable/assets/20944869/e3e9824d-2f29-4752-9e23-87e7d86f4f4b" width=400 />
<br />
<br />

I understand, that iIdeally when there is some value that would expand the column width you would like to have this layout:

<image src="https://github.com/oleksandrbalan/lazytable/assets/20944869/d4ef7c6a-fe48-469e-89b4-fa63919112b8" width=400 />
<br />
<br />


However you will need to render every item in the layout to measure the largest one and adjust the cell size, which defeats the purpose of the lazy layout 🤷‍♂️ 

What you can do, is to pre-measure the expected content and set cell size based on your measurements. I played around with this idea in [one of the ProgramGuide examples](https://github.com/oleksandrbalan/programguide/blob/main/demo/src/commonMain/kotlin/eu/wewox/programguide/demo/screens/ProgramGuideSizeScreen.kt). 

Similarly you could try to pre-calculate the needed width / height and set to your lazy table to match your data.

https://github.com/oleksandrbalan/lazytable/assets/20944869/004db7c9-5355-4ee7-a46b-f0ece97a9b31

**Comment by ikerfah** [comment]
Thanks for the example, it is working as expected! thanks for your help!
